<?xml version="1.0" encoding="utf-8"?><Database Name="MyShoeStoreDB" Class="KidShoesDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-P4F5KURV;Initial Catalog=MyShoeStoreDB;Integrated Security=True;Pooling=False;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyShoeStoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KidShoes" Member="KidShoes">
    <Type Name="KidShoe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Material" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inStock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>