// <auto-generated />
namespace Re_Frameworks_Exs_ForTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TheSportShoesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TheSportShoesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201161905387_TheSportShoesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
